version: '3.8'

services:
  react-server:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./react/app:/app
    depends_on:
      - fastapi

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./fastapi/src:/usr/app
    expose:
      - 4000
    depends_on:
      - db


  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - ./fastapi/db:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5432:5432"
