version: '3.8'

services:
  react-server:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./react/app:/app
    depends_on:
      - fastapi

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./fastapi/app:/app
  ch_server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
    volumes:
      - ./fastapi/db:/var/lib/clickhouse
  ch_client:
    image: yandex/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity

