version: '3.8'

services:
  react-server:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./react/app:/app
    depends_on:
      - fastapi

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./fastapi/src:/usr/app
    expose:
      - 4000
    depends_on:
      - mongodb


  mongodb:
    image: mongodb/mongodb-community-server:latest
    environment:
      - ${MONGO_INITDB_ROOT_USERNAME}
      - ${MONGO_INITDB_ROOT_PASSWORD}
      - ${MONGO_HOST}
      - ${MONGO_DB}
      - ${MONGODB_URL}
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./fastapi/db_dir
        target: /data/db
